version: '3.4'

services:
  nextcloud-api-prd:
    image: ${DOCKER_REGISTRY-}
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:80"
    networks:
      apinetwork:
        ipv4_address: 172.21.0.9
    ports:
      - "5828:80"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always

networks:
  apinetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
